#!/usr/bin/perl

use Modern::Perl;

use Data::Dumper;
use File::Basename;
use Getopt::Long;

my $help;
my $verbose = 0;
my $koha_account;
my $sql_file;

GetOptions(
    "k|koha|koha-acount=s" => \$koha_account,
    "f|file=s"             => \$sql_file,
    "verbose+"              => \$verbose,
    "help"                 => \$help
) or die("Error in command line arguments\n");

if ($help) {
    print_help();
    exit;
}

unless ( $koha_account ) {
    print_help();
    say "-k or required";
    exit;
}

say "Using koha account $koha_account"   if $verbose;

say "Importing SQL file $sql_file ..." if $verbose;

my $filename= substr($sql_file, rindex($sql_file,"/")+1, length($sql_file)-rindex($sql_file,"/")-1);
my $command = qq(docker cp $sql_file koha-$koha_account:/.);
say "COMMAND: $command" if $verbose > 2;
my $output = qx{$command};;
say "Copied $sql_file to koha-$koha_account: $output" if $verbose > 1;

$command = qq{ docker exec koha-$koha_account bash -c "zcat /$filename | egrep -v '^(CREATE DATABASE|USE|INSERT INTO \\\`action_logs|INSERT INTO \\\`import_records|INSERT INTO \\\`statistics|INSERT INTO \\\`deletedbiblio|INSERT INTO \\\`deleteditems)' - | sudo koha-mysql $koha_account" };
say "COMMAND: $command" if $verbose > 2;
$output = qx{$command};
say "Imported file: $output" if $verbose > 1;

say "Importing complete!" if $verbose;

sub print_help {
    say "$0 -k <koha account> -v -f /path/to/file.sql.gz";
}
