#!/usr/bin/perl

use Modern::Perl;

#use XML::Hash;
use Getopt::Long;
use Data::Dumper;

my $help;
my $verbose = 0;
my $koha_account;
my $bws_shortname;
my $sql_file;

GetOptions(
    "k|koha|koha-acount=s" => \$koha_account,
    "s|shortname=s"        => \$bws_shortname,
    "f|file=s"             => \$sql_file,
    "verbose"              => \$verbose,
    "help"                 => \$help
) or die("Error in command line arguments\n");

if ($help) {
    print_help();
    exit;
}

unless ( $koha_account || $bws_shortname ) {
    print_help();
    say "-k or -s required";
    exit;
}

$koha_account  ||= $bws_shortname;
$bws_shortname ||= $koha_account;

say "Using koha account $koha_account"   if $verbose;
say "Using bws shortname $bws_shortname" if $verbose;

#my $koha_conf = "/etc/koha/sites/$koha_account/koha-conf.xml";

#die("Cannot read $koha_conf!") unless -r $koha_conf;

#my $xml_converter = XML::Hash->new();
#my $koha_config   = $xml_converter->fromXMLStringtoHash($koha_conf);

#my $mysql_username = $koha_config->{yazgfs}->{config}->{user}->{text};
#my $mysql_password = $koha_config->{yazgfs}->{config}->{pass}->{text};

unless ($sql_file) {
    $sql_file = "/home/bywater/bwsbackups/$bws_shortname-db.sql.gz";
    unless ( -r $sql_file ) {
        $sql_file = "/home/bywater/bwsbackups/$bws_shortname.sql.gz";
        unless ( -r $sql_file ) {
            die("Cannot read $sql_file!") unless -r $sql_file;
        }
    }
}

say "Importing SQL file $sql_file ..." if $verbose;
my $command = "zcat $sql_file | egrep -v '^(CREATE DATABASE|USE|INSERT INTO \`action_logs|INSERT INTO \`import_records|INSERT INTO \`statistics)' - | sudo koha-mysql $koha_account";
system($command);

say "Importing complete!" if $verbose;

sub print_help {
    say "$0 -k <koha account> -s <bws shortname> -v -f /path/to/file.sql.gz";
}
