#!/usr/bin/perl

=head1 NAME

devbot - a bot to let us know what's going on in the dev server

=head1 DESCRIPTION

This bot will alert us when given actions are taken on the dev server

Requires /tmp/devbot be a named pipe for communication

=cut

use Modern::Perl;

use POSIX qw(mkfifo);

# Create and run the bot
Bot->new(
    channels => [ '#bywater', '#bws-partners' ],
    nick     => 'devbot',
    server   => 'irc.oftc.net',
)->run;

# Here's the definition of the bot
package Bot;
use base qw(Bot::BasicBot);

sub tick {
    my $self = shift;


    open( FIFO, "< /tmp/devbot" ) or die $!;
    while (<FIFO>) {
        my $body = "$_";
        $self->say( channel => $_, body => $body )
          for ( @{ $self->{channels} } );
    }
    close(FIFO);

    # Yes, I know this sub will never return
    return 5;
}

